<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite001-LoginMenu</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ec4b7c91-5f34-4303-8f32-ff7928a1b5fa</testSuiteGuid>
   <testCaseLink>
      <guid>6d25f156-660f-4ca2-b1e1-85bf0a7acf0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Positive/TC001-LoginMenu-Positive-UserLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>84d693c4-6b23-4168-a9d0-60f46d86e84e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login-OrangeHRM</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>84d693c4-6b23-4168-a9d0-60f46d86e84e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>d3955765-88b2-4e5d-b09a-a664963fdaa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>84d693c4-6b23-4168-a9d0-60f46d86e84e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>92f514b6-8c2b-4d81-b205-e3ff58a2e55c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de59e749-34b7-496e-bf40-445af93adf15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Positive/TC002-LoginMenu-Positive-ForgotPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>32488e65-1d4a-4c22-beaa-76a0dd587c86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Positive/TC003-LoginMenu-Positive-ValidateLabelUsername</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ffe293b9-6c0c-4fc3-94b8-b9582dae0d45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Positive/TC004-LoginMenu-Positive-ValidateLabelPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>de7d7b3e-8ec4-4aa4-9613-3d29cbd2d57c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Positive/TC005-LoginMenu-Positive-UserLogin-ValidCredential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bda5f587-9a09-48f0-ae02-234f8a273f40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Negative/TC001-LoginMenu-Negative-InvalidUsername</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1c5f04d2-ba85-4eaa-bcc3-3e914d4db554</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login-OrangeHRM</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1c5f04d2-ba85-4eaa-bcc3-3e914d4db554</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>invalid_username</value>
         <variableId>373a8fda-3a6a-4f0a-b62c-530a44318801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1c5f04d2-ba85-4eaa-bcc3-3e914d4db554</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>57b79c65-5a25-412e-a28f-7d5941496fc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1c5f04d2-ba85-4eaa-bcc3-3e914d4db554</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>alert_failed_invalid</value>
         <variableId>dc361ce3-7dc2-4dd2-84a1-8006624623f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63b8916a-8e2d-4c3f-b5b0-6b7b4af427f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Negative/TC002-LoginMenu-Negative-InvalidPassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>800fdf9f-1fdc-44f7-ad65-240afec91bfc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login-OrangeHRM</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>800fdf9f-1fdc-44f7-ad65-240afec91bfc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>551590b0-51a4-41d3-bcf3-d759a8166c3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>800fdf9f-1fdc-44f7-ad65-240afec91bfc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>invalid_password</value>
         <variableId>3a7619d1-22fb-4085-a82d-4f8b5a1d9df0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>800fdf9f-1fdc-44f7-ad65-240afec91bfc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>alert_failed_invalid</value>
         <variableId>d867ea34-93ae-43d1-aac9-d41beb3fda72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>098b4cd6-5728-4d63-9415-205ec2e193c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Negative/TC003-LoginMenu-Negative-NullUsername</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bdabaf76-0ce3-4d6c-b769-fe5832316708</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login-OrangeHRM</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bdabaf76-0ce3-4d6c-b769-fe5832316708</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nodata</value>
         <variableId>d8e97df4-c357-4b90-8a8b-95db0636a889</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdabaf76-0ce3-4d6c-b769-fe5832316708</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>46347b1d-3771-4055-9925-bb967c36378d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdabaf76-0ce3-4d6c-b769-fe5832316708</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>alert_failed_null</value>
         <variableId>4b0fe51c-c6db-47da-9d30-abfd921ab378</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a74f0a92-b55c-4c4f-b517-d2ec073cce1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Negative/TC004-LoginMenu-Negative-NullPassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>34420d93-e7f4-4c6c-a0ca-31e9287cbf43</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login-OrangeHRM</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>34420d93-e7f4-4c6c-a0ca-31e9287cbf43</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>cd9b1177-3273-49d5-97dd-b7069e462833</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>34420d93-e7f4-4c6c-a0ca-31e9287cbf43</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nodata</value>
         <variableId>b56706e0-a82d-43c0-a957-64c766e463ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>34420d93-e7f4-4c6c-a0ca-31e9287cbf43</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>alert_failed_null</value>
         <variableId>8a8a12ce-360f-43bc-a943-157d109a5e99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87a4b978-bc35-406c-afbc-4fd76a36e52c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Negative/TC005-LoginMenu-Negative-NullUsernamePassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>87c42f5a-d3da-47d9-84a3-c0e8ac6f51ec</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login-OrangeHRM</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>87c42f5a-d3da-47d9-84a3-c0e8ac6f51ec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nodata</value>
         <variableId>8b2d9bdd-ad57-45af-99b3-03741fe1a66d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>87c42f5a-d3da-47d9-84a3-c0e8ac6f51ec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>alert_failed_null</value>
         <variableId>228dd92b-381d-4b89-b10a-b215a6d10b22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a61c77c4-a03a-4e35-b48b-af80a3e56829</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/project/OrangeHRM/LoginMenu/TC-Negative/TC006-LoginMenu-Negative-InvalidUsernamePassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1ef9431e-8258-415c-b4e2-214459e0cedf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login-OrangeHRM</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1ef9431e-8258-415c-b4e2-214459e0cedf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>invalid_username</value>
         <variableId>71558392-d062-4183-b038-8fb55d8b5d16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ef9431e-8258-415c-b4e2-214459e0cedf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>invalid_password</value>
         <variableId>bbcd897c-3d57-427a-9638-ae9756d238b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ef9431e-8258-415c-b4e2-214459e0cedf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>alert_failed_invalid</value>
         <variableId>784bc5be-e5d2-4401-8232-8b83add4c83b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
